
ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS auth_provider_id UUID REFERENCES auth_providers(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS provider_user_id TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;